### ISSUE TITLE
Can 'src' attribute be relative to gruntfile

### ISSUE THREAD

**Issue by helgatheviking** [zonak/grunt-ftp-deploy#101]
Currently you have to look up the path for the source folder

`src: 'path/to/source/folder',`

It could be useful to accept paths relative to the Gruntfile. In my case, I am usually uploading the folder containing the gruntfile itself... or would possibly want to upload only a portion of that folder.

**Comment by zonak** [comment]
The paths are relative to the root of the project (which is the location that should contain the gruntfile) but I would advise against it because this would be also the most likely location of potential password files and even `node_modules`.
