### ISSUE TITLE
Single File

### ISSUE THREAD

**Issue by Gouvi** [zonak/grunt-ftp-deploy#102]
Hey,

I'm looking at tracking a single file. I'm using grunt watch and wish to trigger grunt-ftp-deploy to update a single file instead of the entire directory. I know that I can exclude a lot of file paths etc, however, the time it takes for it to scan over the directory, perform the ftp, is taking too long for what I need it for.

Any help would be great, thanks!

**Comment by zonak** [comment]
Copy it to a temp folder.

**Comment by Gouvi** [comment]
It's style.css, for a Wordpress Template, so I need to upload it to the themes root directory.

**Comment by zonak** [comment]
And you can still do so if you have a temp folder with a single file as the originating location.

**Comment by KarelWintersky** [comment]
it's not a correct solution :(

**Comment by zonak** [comment]
Why? Grunt does a lot of things with temp folders - why is having the file
in a temp folder and deploy that not a solution?

**Comment by KarelWintersky** [comment]
because my html file is not builded by any grunt script. 

My quest: upload a single file with nodejs without VERY LARGE AND POWERFUL libraries

**Comment by zonak** [comment]
You don't have to build it - you can just copy it. Not sure why is that a
problem, you already have everything necessary in place, it doesn't take
"VERY LARGE AND POWERFUL libraries"

**Comment by KarelWintersky** [comment]
you can't understand my problem.
