### ISSUE TITLE
forceVerbose doesn't work

### ISSUE THREAD

**Issue by covertbert** [zonak/grunt-ftp-deploy#104]
Unfortunately forceVerbose doesn't seem to do anything.

**Comment by zonak** [comment]
I hate to give you an answer of the type "It works for me" but it really does. Not sure what is the problem especially since you are not sharing any details.

**Comment by covertbert** [comment]
Apologies that was somewhat vague!

The section in my gruntfile looks like this:

    'ftp-deploy': {
			zips: {
				auth: {
					host: 'host.com',
					port: 21,
					authKey: 'key1',
					forceVerbose: true
				},
				src: './irep/zips',
				dest: '/'
			}
		},

and my output looks like this:

    Running "ftp-deploy:zips" (ftp-deploy) task
    >> FTP upload done!

    Done, without errors.

Perhaps I'm misunderstanding what should be happening, but I assumed it would output much the same as what you'd get by running `grunt ftp-deploy -vv`

**Comment by zonak** [comment]
Put the `forceVerbose` options under `dest` - it needs to be one level up, it is not an authorization parameter.

**Comment by covertbert** [comment]
Ahhh right that works perfectly, sorry I should have noticed that! Cheers for the help
