### ISSUE TITLE
Upload changed files only

### ISSUE THREAD

**Issue by mikaoelitiana** [zonak/grunt-ftp-deploy#107]
It would be nice if the task upload only changed files when I do a new deploy.

**Comment by julmot** [comment]
How should this work in detail? ftp-deploy should save the file sizes of your deploy folder and check against differences on each deploy?

**Comment by mikaoelitiana** [comment]
Yes that would be a good process. Another solution would be using git diff. ftp-deploy would store latest git commit after upload is done and check this when starting a new upload. What do you think?

**Comment by julmot** [comment]
I think a git comparison goes too far and should be a separate task. I can imagine that ftp-deploy compares the src and dest folder first and uploads only the delta files (based on file timestamp). @zonak What do you think?

**Comment by zonak** [comment]
The main purpose of this task for me when I first started it was to fulfill a need. The need was to deploy files that are a product of a build process which are not tracked by git. Also the destination I had to deal with didn't have git, rsync on anything like that.
Going into the direction of making diffs defies the purpose and the need for this task.
If you track the files you need to deploy with git then you can easily deploy them with something like git hooks.
Timestamps are another direction but considering that time is not always perfectly configured everywhere in addition to time differences - it creates a whole other level of complexity.
At the end of the day the purpose is to have a simple deploy of the results of a build process.

**Comment by julmot** [comment]
As I already mentioned I agree that a git comparison should be a separate task.
But I think - regardless of what property (timestamp, size, etc.) - a simple src and dest comparison would be useful. The task could work with already existing comparison tasks like [this](https://github.com/rwaldron/grunt-compare-size) or [this](https://github.com/Risto-Stevcev/grunt-file-compare).

**Comment by konstantin24121** [comment]
+ This option will be great.

**Comment by zonak** [comment]
This has been discussed and addressed before. It is not in the scope of the task.

**Comment by julmot** [comment]
@zonak we have not yet fully rejected this (see my previous comment).
