### ISSUE TITLE
Ability to upload specific files instead of whole folder.

### ISSUE THREAD

**Issue by TanKucukhas** [zonak/grunt-ftp-deploy#110]
That would be nice to be able to only upload certain files depending on the situation. For example I sometimes need to compress a pack of files and just need to upload the zip file, or even in some cases do a comparison on the folder and only upload the files that are changed to save time and not upload the whole folder.

**Comment by zonak** [comment]
This has been answered numerous time. Use a "copy" task and put the files you need in a temp folder - grunt uses this approach for a lot of things.
