### ISSUE TITLE
Allow Backslash in FTP username

### ISSUE THREAD

**Issue by chriskarkowsky** [zonak/grunt-ftp-deploy#118]
If possible, please allow the use of a backslash in an FTP username.  This is the format given by an Azure Web App, where you specify the webappname\username.  This seems to only happen when defined in .ftppass.  If you leave out the credentials and type manually when prompted, it will work.

The task will abort due to warnings with whatever letter comes after the backslash:

\SiteAdmin>grunt restartbeta
Running "ftp-deploy:beta" (ftp-deploy) task
Warning: Unexpected token S Use --force to continue.

Aborted due to warnings.

**Comment by zonak** [comment]
Did you try escaping it with double backslash?

**Comment by chriskarkowsky** [comment]
Yes, double backslash will cause the prompt for the username:
  "ftpbetacreds": {
    "username": "xxxxxx\\yyyyyyy",
    "password": "zzzzz"
  }

SiteAdmin>grunt restartbeta
Running "ftp-deploy:beta" (ftp-deploy) task
prompt: username:

**Comment by chriskarkowsky** [comment]
You can't actually see the double escape in the post :)

**Comment by chriskarkowsky** [comment]
You can't actually see the double escape in the post :).  Only when editing it...

**Comment by chriskarkowsky** [comment]
Sorry, issue with my code.  Escaping does in fact work.  Thanks! :)
