### ISSUE TITLE
Error when trying to upload folders

### ISSUE THREAD

**Issue by mcat** [zonak/grunt-ftp-deploy#15]
Here's what the console is printing out:

```
Running "ftp-deploy:build" (ftp-deploy) task
Uploaded file: file1.html to: /
Uploaded file: file2.html to: /
Uploaded file: file3.xml to: /
Uploaded file: file4.txt to: /
Uploaded file: file5.html to: /
Uploaded file: file6.txt to: /
Uploaded file: file7.html to: /
Error creating new remote folder folder/css --> Error: 550 folder/css: No such file or directory
Warning: Could not switch to remote folder! Use --force to continue.
```

Individual files at the root of the src folder are successfully copied over from the src folder to the dest folder on the remote server.  But if there are any folders in the src folder the process fails at the folder.

Any ideas what could be causing this?

Here's what my config looks like:

```
'ftp-deploy': {
        build: {
            auth: {
                host: server.com',
                port: 21,
                authKey: 'key1'
            },
            src: 'build',
            dest: folder'
        }
    }
```

**Comment by Hardbitrocker-zz** [comment]
same problem different solution.
...
src: 'build'
dest: 'domain.com/files/Layout'
...
with checking the permissions of the files the path shown in the ftp client was:
'/home/www/domain.com/files/Layout'

Writing this to 'dest' did the trick for me.
