### ISSUE TITLE
Sending a single file

### ISSUE THREAD

**Issue by fredw** [zonak/grunt-ftp-deploy#32]
Hi,

You can perform the sending of a single file?
I tried to configure the sending of a single file and I returned the following error:

`Warning: ENOTDIR, not a directory ...`

This is an example of what I'm trying to do:

<pre>
'ftp-deploy': {
    config: {
        auth: {
            host: 'ftp://domain.com',
            port: 21,
            authKey: 'key1'
        },
        src: './includes/config.php',
        dest: 'includes/config.php'
    }
}
</pre>

Thanks!

**Comment by JaakkoKarhu** [comment]
Disagreed. What if I want to deploy just parts of the project, ie. some style files which are modified? Why would I want to toss all the php in at the same time?

**Comment by zonak** [comment]
>
> You can always create a temp folder with just the files you want deployed
> - this is a very common pattern for grunt.
>

Z
