### ISSUE TITLE
Upload a single file

### ISSUE THREAD

**Issue by piuccio** [zonak/grunt-ftp-deploy#72]
Would you consider adding the possibility to upload a single file instead of a whole directory?

**Comment by Baba43** [comment]
It would be great to have an option like *inclusions* or *filter* like we have with *exclusions*. I tried to upload a single file with the *exclusions* option but I could not get it working.

**Comment by zonak** [comment]
It is very easy to achieve this as mentioned with a temp folder. There is no reason to complicate things when there is a way to do what you are asking for.
