### ISSUE TITLE
.ftppass not working where username and password are empty strings..

### ISSUE THREAD

**Issue by peteobrien** [zonak/grunt-ftp-deploy#74]
So it's pretty minor; to skip have to press enter, enter to enter a blank username and password. But I think it has a valid use case: logged in on a network, and a new developer not aware username and password are unrequired

And at least I think it's not working. I have the following:

In `Gruntfile.js`

```
grunt.initConfig({
    'ftp-deploy': {
      build: {
        auth: {
          authKey: "key1"
          ...
```

In `.ftppass`

```
{
  "key1": {
    "username": "",
    "password": ""
  }
}
```

but I'm still being prompted for username and password.

**Comment by peterobrien** [comment]
Not fixed here by the seem of it
