### ISSUE TITLE
Unexpected string error

### ISSUE THREAD

**Issue by bl4ckdu5t** [zonak/grunt-ftp-deploy#84]
I have the following Gruntfile.js file

```javascript
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    uglify: {
      options: {
        banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
      },
      build: {
        src: 'js/built.js',
        dest: 'js/script.min.js'
      }
    },
    concat: {
      options: {
        separator: ';',
      },
      dist: {
        src: ['js/vendor/jquery-2.1.1.min.js', 'js/vendor/responsiveslides.min.js', 'bower_components/owl-carousel/owl-carousel/owl.carousel.js','bower_components/lightbox/js/lightbox.js','js/script.js'],
        dest: 'js/built.js',
      },
    },
    'ftp-deploy': {
      build: {
        auth: {
          host: 'oyepng.org',
          port: 21,
          authKey: 'key1'
        },
        src: './',
        dest: './',
        exclusions: ['.gitignore', '.sass-cache']
      }
    },
  });

  // Load the plugins
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-ftp-deploy');

  // Default task(s).
  grunt.registerTask('default', ['concat','uglify']);

};

```
and while all my other Grunt tasks run successfully, the `grunt 'ftp-deploy'` gives me the following error:
```
Running "ftp-deploy:build" (ftp-deploy) task 
Warning: Unexpected string Use --force to continue. 
Aborted due to warnings.
```
What could be responsible for this?

**Comment by zonak** [comment]
What is `ftpush`? I don't see it defined and yet you have it in your call.

**Comment by bl4ckdu5t** [comment]
I'm sorry I had put a different thing from a different app where I tried that task. I've adjusted it to show the way it appears exactly with ftp-deploy

**Comment by zonak** [comment]
In any case you need to go over your configuration - this is not an issue with the task itself. I would recommend to also look into the logon info too and make sure everything is correct there.

Based on what you have provided I can't see what the issue is.

**Comment by bl4ckdu5t** [comment]
You mean the .ftppass file right? Am I not meant to get an error like 'incorrect credentials' if the logon info is wrong or 'file not found' if it doesn't see the file? Really will love to see this working but it if the failure persists, I'll grab the good o'l way. Thanks

**Comment by zonak** [comment]
The password file needs to be properly formatted JSON file even to the extent of using only double quotes …

I would really like to help but without the proper details I can only give you recommendations ...


<z/>

On January 29, 2015 at 11:39:51 AM, Joseph Rex (notifications@github.com) wrote:

You mean the .ftppass file right? Am I not meant to get an error like 'incorrect credentials' if the logon info is wrong or 'file not found' if it doesn't see the file? Really will love to see this working but it if the failure persists, I'll grab the good o'l way. Thanks

**Comment by bl4ckdu5t** [comment]
I could send you my .ftpass but I wouldn't want to do that on a public issue. I will close the issue now and will love to send you emails instead. You can send hi to me at joerex [at] ostrich-dev [dot] com and I'll take it from there
