### ISSUE TITLE
should be able to set verbosity via an options hash?

### ISSUE THREAD

**Issue by peterobrien** [zonak/grunt-ftp-deploy#85]
We found the old verbosity useful and run `ftp-deploy` within an array of other tasks. It'd be useful to be able to easily set just verbose to `true` for the `ftp-deploy` task. Adding an `options` hash with `verbose:true` doesn't seem to work. (Seems to me the only way is to achieve this is to register a `verbose` task and run before and after `ftp-deploy` ? )

**Comment by peterobrien** [comment]
Or perhaps this is standard and we should be using ~ like https://www.npmjs.com/package/grunt-verbosity ?

**Comment by zonak** [comment]
I am not sure I understand the issue - passing the `--verbose` parameter when running `grunt` should do it. I might be misunderstanding something.

**Comment by peterobrien** [comment]
Hi,

Apologies for my lack of clarity. 

It's really not a big issue but in terms of having intimate control a bit annoying.

We do not run the `ftp-task` on its own. We run it alongside a few other tasks.

We find `ftp-deploy`'s verbosity useful but the other task's verbosity not useful. So to run everything with `--verbose` gives a lot of stuff we're not interested in.

We'd like for only the `ftp-deploy` task to run in `verbose` mode.

It'd be nice if we could specify this within an `options` configuration object within the `ftp-deploy` configuration's object.

I'm not sure if this is standard feature found in other plugins or not.

Thanks
Peter

**Comment by zonak** [comment]
Made some changes to address your use case here https://github.com/zonak/grunt-ftp-deploy/commit/f8a3e6545ef9553b02b0c042d3992d8c2abb5a39
It is now published to _npm_ as well so give it a go and let me know how it goes.

**Comment by peterobrien** [comment]
That works great. Thanks.
