### ISSUE TITLE
Cannot upload file: rectangle1.png --> Error: read ECONNRESET

### ISSUE THREAD

**Issue by SubZane** [zonak/grunt-ftp-deploy#86]
I cannot get this to work properly. It uploads all files fine in about 10% of the time. The other 90% of the time I get the error

Cannot upload file: rectangle1.png --> Error: read ECONNRESET

I'm not sure if I'm doing something wrong or not

**Comment by charliedowler** [comment]
How big is the file / Have you checked it's not corrupted?

Cheers

**Comment by SubZane** [comment]
It's a PNG picture around 500kb and can be viewed in the browser and photoshop so I don't think it's corrupt. It can be uploaded using my ftp client

**Comment by charliedowler** [comment]
If you exclude `rectangle1.png`, does it upload the rest as expected?

**Comment by SubZane** [comment]
Almost, now it failed on "cannot upload file: fontawesome-webfont.eot --> Error: read ECONNRESET"

It seems that it cannot overwrite existing files?

**Comment by charliedowler** [comment]
Permissions issue?

**Comment by SubZane** [comment]
could be maybe. The error message is cryptic at best :)

I'm using the same ftp user/pass on my ftp client that I give to grunt-ftp-deploy so I would assume there wouldn't be any problems with permissions. hmm

**Comment by charliedowler** [comment]
It might be the a permissions issue from files already on the server.

Open your FTP client and look at the permissions, the pre-existing files may have a different owner. You could run a chmod on all the files to and re-assign the owner to your login.

**Comment by SubZane** [comment]
This is a capture from two files. One is uploaded using ftp-deploy, the other is uploaded using my ftp program.

![screen](https://cloud.githubusercontent.com/assets/90636/6146876/db88184a-b1f1-11e4-9fc8-0bb60494c425.png)

**Comment by zonak** [comment]
I understand that the message from the task is not too descriptive but this is what we get from the underlying `jsftp` layer.

You have a better chance of figuring out what is going on by looking at the logs on the server. Maybe even compare logs when you upload files via the task and another FTP client.

**Comment by SubZane** [comment]
I'll check the server logs and get back to you

does grunt-ftp-deploy produce its own log perhaps?

**Comment by zonak** [comment]
The task is essentially a wrapper around `jsftp` - so if there is an issue with the transport layer (which is what it looks like) I think you next efforts should be directed towards `jsftp`.
