### ISSUE TITLE
Warning: 'authKey' configuration provided but no valid '.ftppass' file found!

### ISSUE THREAD

**Issue by vlrprbttst** [zonak/grunt-ftp-deploy#87]
on the root of my project i've created this file: ftp.ftppass

inside of it, there's this code:
{
build : {
  "key1": {
    "username": "username",
    "password": "****"
  }
}
}

and here's my gruntfile.js task

		pkg : grunt.file.readJSON('package.json'),

		'ftp-deploy' : {
			build : {
				auth : {
					host : 'ftp.mywebsite.com',
					//port : 21,
					authKey : 'key1'
				},
				src : './',
				dest : '/www',
				exclusions : ['.sass-cache', '_PSD', 'cv', 'node_modules', 'ftp.ftppass', 'twitterfeed', 'gruntfile.js', 'package.json']
			}
		},

[...]

i got this error: Warning: 'authKey' configuration provided but no valid '.ftppass' file found!

i'm pretty sure it's something very stupid but i can't figure it out. any help would be greatly appreciated :)

**Comment by charliedowler** [comment]
Your ftp file should be named: `.ftppass`

**Comment by vlrprbttst** [comment]
http://prntscr.com/63z8z5 on windows, files need a name -- how do i get his around?

**Comment by charliedowler** [comment]
Create the file using `notepad` > Save As `.ftppass`

**Comment by zonak** [comment]
You might want to skip the "build" level in your auth object ... You have a key and a object with username and password as value.

**Comment by vlrprbttst** [comment]
thanks charlie, it worked!
thanks zonak, i removed the build from the .ftppass file cause i got an error.

now i'm stuck here: http://prntscr.com/63zblw - nothing happens
