### ISSUE TITLE
stuck on Running "ftp-deploy:build" (ftp-deploy) task

### ISSUE THREAD

**Issue by vlrprbttst** [zonak/grunt-ftp-deploy#88]
my grunt file looks like this:

<pre>
pkg : grunt.file.readJSON('package.json'),
		'ftp-deploy' : {
			build : {
				auth : {
					host : 'ftp.site.com',
					port : 21,
					authKey : 'key1'
				},
				src : '.',
				dest : '/www',
				exclusions : ['.sass-cache', '_PSD', 'cv', 'node_modules', '.ftppass', 'twitterfeed', 'gruntfile.js', 'package.json']
			}
		},
</pre>
and my .ftppass (in the root of my project) looks like this:
<pre>
{
  "key1": {
    "username": "usr",
    "password": "***"
  }
}</pre>

i'm stuck here: http://prntscr.com/63zjbd
nothing happens.
what could it be?

thanks!

**Comment by zonak** [comment]
Couple of things I can suggest:

- try using a subfolder as a test - just to make sure you don't have issue with resolving the source of the files (which should be relative to your project root where the `grunt` files reside
- check what is going on the server - check the logs and see if there is anything odd there
- run the task in verbose mode:
```
grunt ftp-deploy:build --verbose
```

**Comment by vlrprbttst** [comment]
thanks for that, after a series of registering and reading tasks, it starts deploying but gets stuck after one, sometimes two or even 3 files: http://prntscr.com/643i6i

is this:

src : '.',

correct? that should be my root. i basically want to deploy anything cointained in the root except the files and folders in the exclusions

**Comment by charliedowler** [comment]
`src: './'` should do the job

**Comment by vlrprbttst** [comment]
ok i'll try that and let you know, thanks a lot!

**Comment by vlrprbttst** [comment]
i did, but it just gets stuck after some file transfer

**Comment by zonak** [comment]
Again ... I would check what is going on on the server - check the logs. The task itself doesn't touch the transport layer - it is just a wrapper around `jsftp`.
Running the task in verbose mode and checking the logs should be your next step. If there is something odd in the logs I would check with the `jsftp` maintainer.

**Comment by vlrprbttst** [comment]
very noob question: how do i check the logs on the server?

**Comment by zonak** [comment]
It really depends on the FTP server you're using. Just look it up in its docs.

**Comment by mikaelec** [comment]
I believe I am experiencing the same problem. I get the following:
```
Running "ftp-deploy:dist" (ftp-deploy) task
Verifying property ftp-deploy.dist exists in config...OK
Files: ./local/dist -> ./ftp_dir
Reading local\.ftppass...OK
>> Uploaded file: a.js to: \
>> Cannot upload file: b.htm --> Error: read ECONNRESET
Warning: Failed uploading files! Use --force to continue.
```

It differs how many files are uploaded before the error is thrown.
Unfortunately I do not have access to FTP logs on my web-hotel.

**Comment by zonak** [comment]
I am sorry but based on what you are providing there isn't enough
information to draw any conclusions.

It could be network issues, it could be permission issues, it could be
something else on the server.
