### ISSUE TITLE
Process finished with exit code 0

### ISSUE THREAD

**Issue by shawnmann** [zonak/grunt-ftp-deploy#89]
I am trying to run ftp-deploy, and it appears to run, but gives me "Process finished with exit code 0" and no files get uploaded. Here are my settings:

"ftp-deploy": {
            qa: {
                auth: {
                    host: 'HOSTINFO',
                    port: PORT,
                    authKey: 'AUTHKEY'
                },
                src: 'build',
                dest: 'testftp'
            }
        }

I am not sure what I am doing wrong - I have tried different src settings, etc. Any help would be awesome.

**Comment by zonak** [comment]
Are you able to run other _grunt_ tasks - because this doesn't look like an error specific to this task.

**Comment by shawnmann** [comment]
Yep, I run other ones fine. If my settings look ok, I will take a look at the ftp server. Thanks!

**Comment by zonak** [comment]
It looks like the message is not an indication of a problem:

<http://gruntjs.com/api/exit-codes>

But looking at the server logs to see what is going on with the uploads is the best approach.

**Comment by shawnmann** [comment]
I will check. Thanks!
