### ISSUE TITLE
503 Bad Sequence of commands

### ISSUE THREAD

**Issue by SWGFL** [zonak/grunt-ftp-deploy#90]
Uploading files mostly doesn't work due to this error.

The FTP log shows the following:

pasv
227 Entering Passive Mode (37,128,134,116,250,78)
stor reports.view.php
150 Opening data channel for file upload to server of "/test/application/reports/reports.view.php"
226 Successfully transferred "/test/application/reports/reports.view.php"
cwd /test/application/reports/javascript
250 CWD successful. "/test/application/reports/javascript" is current directory.
pasv
227 Entering Passive Mode (37,128,134,116,250,79)
stor gauge.d3.js
150 Opening data channel for file upload to server of "/test/application/reports/javascript/gauge.d3.js"
pasv
227 Entering Passive Mode (37,128,134,116,250,80)
226 Successfully transferred ""
stor reports.js
503 Bad sequence of commands.
disconnected.

Seems to send the PASV command before it has received confirmation of the last transfer. Most of the time it does this after transferring the first file, but sometimes it will get through 20 or 30 files before this error. Any ideas?

**Comment by zonak** [comment]
Previous research on similar problems pointed to the use of proxies as one of the possibilities - are there any proxies involved?
This is not an error specific to the task but a general FTP error so the root of the problem can easily be something else. I have tried to reproduce it but with no success.

**Comment by SWGFL** [comment]
Many thanks for looking into it. Yes there are proxies involved, no probs using Filezilla from the same machine though. Strange that is can upload files, but randomly fails though.

**Comment by zonak** [comment]
FileZilla is a full blown FTP client that is doing much better job at covering a lot more angles than this task does. For the transport layer it uses `jsftp` where you might have better chances at figuring out an answer. Sorry for not being able to offer a more specific solution.

**Comment by SWGFL** [comment]
Thats ok, thanks for taking the time to look into it. Will take the issue over to jsftp.
