### ISSUE TITLE
deploy only new or modified files

### ISSUE THREAD

**Issue by felipeS** [zonak/grunt-ftp-deploy#91]
Is there any way to only deploy new or modified files (Git-liike) or is it too much to ask ?

**Comment by zonak** [comment]
This task is meant for simple deployment. Tracking what is changed and what not and persisting this info between deploys can easily get out of hand which is why it has never been the goal.

Something like git or rsync is probably the way to go for that purpose.

**Comment by DrChills** [comment]
Seconded

surely checking for different size / new file isn't a step to far and would certainly help a fair few people!

I certainly don't think tracking changes would be useful though - like you say, Git is better way to go...

**Comment by zonak** [comment]
I don't think the file size is a sufficient guarantee for determining if a file has changed. Also going that route would make the whole process much much slower.

Anyway ... I think there are better tools to address this need if necessary.

**Comment by DrChills** [comment]
Can you advise the tools? I'd like to keep it all in my grunt workflow but grunt-newer doesn't seem to work over ftp

**Comment by zonak** [comment]
I just did a quick search and found this:

<https://github.com/jedrichards/grunt-rsync>

and most likely there are a lot more. You just need to go by what's available for you. I didn't have the commodity of using something like `rsync` but if you do - it is a good approach.
