### ISSUE TITLE
feature request: add caching similar to grunt-sftp-deploy

### ISSUE THREAD

**Issue by rkoberg** [zonak/grunt-ftp-deploy#94]
https://github.com/thrashr888/grunt-sftp-deploy

The readme says the project is basically a copy of your project, but they have caching. Any chance you can reuse their code and add to this code base?

cache - boolean/string - put false or omit this parameter for no cache, otherwise provide path to cache file, so overwriten are only the files that has been changed (it works only for your local copy, so if someone else uploaded something meanwhile it will not be catched). Path is relative to your gruntfile, so you can easily clear cache by erasing this json file. This file should be omitted from source control.

**Comment by zonak** [comment]
I am sorry but this is changing the scope of the task. The caches and similar methods are not reliable enough to rely on for things like deployment. With a little bit of better organization you wouldn't need it.
