### ISSUE TITLE
Upload a single file

### ISSUE THREAD

**Issue by AurelioDeRosa** [zonak/grunt-ftp-deploy#95]
The `src` property requires a folder but sometimes you want to upload just one file. At the moment the task raises an error when a single file is specified.

**Comment by AurelioDeRosa** [comment]
Closing as a duplicate of https://github.com/zonak/grunt-ftp-deploy/issues/72. Sorry about that.

**Comment by zonak** [comment]
>
>
> Grunt already makes often use of temp folders - copy your file to a temp
location and upload from there.

>
>
