### ISSUE TITLE
Console user/pass

### ISSUE THREAD

**Issue by ImanMh** [zonak/grunt-ftp-deploy#96]
Please add this feature so that we can give user and password in console when the task is ran and there is no username and password field defined in task config.  
Writing down user name and password in text based files is not secure and makes issues when we want to share our grunt file with team members that don't have access too ftp.

**Comment by zonak** [comment]
If you don't have the `authKey` property defined in the configuration and run the task it will ask you for a username and a password.

**Comment by ImanMh** [comment]
Thanks for your response. Here is my configuration object: 
```javascript
    'ftp-deploy': {
      build: {
        auth: {
          host: 'server.com',
          port: 21
        },
        src: 'node_modules',
        dest: '/path/to/destination/folder',
        exclusions: ['path/to/source/folder/**/.DS_Store', 'path/to/source/folder/**/Thumbs.db', 'path/to/dist/tmp']
      }
    }
```

and this is what I get after running ftp task: 

![screen shot 1394-02-27 at 12 24 31](https://cloud.githubusercontent.com/assets/4482199/7669578/afcffb26-fc8f-11e4-96a7-a8e4e2091e0e.png)

**Comment by zonak** [comment]
This is a firewall issue most likely.

**Comment by ImanMh** [comment]
Thank you very much, it's because I gave it a dummy host. Sounds like ftp deploy is smart enough to check if it can do it's job without a username and password so it does not ask for user/pass before checking remote server.
