### ISSUE TITLE
Allow functions for src and dest

### ISSUE THREAD

**Issue by MarkRabey** [zonak/grunt-ftp-deploy#98]
I have a case where my source and destination are potentially different depending on the language (in my case English and French. Allowing a function to be used for these options would allow me to call the a single deployment without the need for otherwise duplicate tasks.

Rough example might look something like:

```
'ftp-deploy': {
    build: {
        auth: {
            ...
        },
        src: function(language) {
            return 'build/' + language;
        }
    }
}

```

Then called like this:

```
grunt ftp-deploy:build:english
```

I'm going to take a fork and experiment when I can - any objections?

**Comment by zonak** [comment]
You can simply calculate the value and use it in the task configuration as a string. The whole _grunt_ config file is just JavaScript where you can have code executed out of the task configuration so I don't think there is a need for this.
